import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { resolve } from "path";

/**
 * Build config for ESM/CJS library output (dist/index.js, dist/index.cjs).
 * Used by project-theta-fe and other consumers that import theta-theme-default as a module.
 * Types (index.d.ts) are generated by the main build.
 */
export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      "@": resolve(__dirname, "src"),
    },
  },
  build: {
    lib: {
      entry: resolve(__dirname, "src/lib-entry.ts"),
      name: "ThetaThemeDefault",
      fileName: (format) => (format === "es" ? "index.js" : "index.cjs"),
      formats: ["es", "cjs"],
    },
    cssCodeSplit: false,
    rollupOptions: {
      external: [
        "react",
        "react-dom",
        "react/jsx-runtime",
        "next",
        "lucide-react",
        "class-variance-authority",
        "clsx",
        "tailwind-merge",
        "tw-animate-css",
      ],
    },
  },
});
